rcc:
  cc-server-url: http://180.76.36.149
  cc-password: 123456
  logProperties: true
  projectName: test-rcc
  env-name: dev
  cc-version-name: 1.0.0
  enableUpdateCallback: true
  appName: example

spring:
  mvc:
    servlet:
      path: /
server:
  servlet:
    context-path: /